### PR TITLE
fix: ids object construction on casted types

### LINKED ISSUE #1279: bug: pyo3 raise
To reproduce, checkout to https://github.com/kkrt-labs/keth/pull/1271 and 
` uv run --reinstall pytest -k ecpairing_inputs_d22g0v0_Cancun -vvvvvvvv -s -log-cli-level="TRACE"`

Image

### LINKED ISSUE #1297: bug: ids object fails de-referencing 0 pointers
```
        %{
            if ids.err.value == 0:
                logger.trace_cairo(f"OpEnd")
        %}
```

running this fails if err.value == 0 (as it's not a pointer, i guess?)

### PR DESCRIPTION
**Pull request by enitrat**
Closes #1297
Might close #1279

### CODE REVIEW

File: crates/cairo-addons/src/vm/vm_consts.rs [hunk 1]
```diff
@@ -322,15 +320,16 @@ impl PyVmConst {
...
-
-                Ok(Some(addr))
+                // Note: if the variable is NOT a pointer (e.g. we cast something to a pointer),
+                // like tempvar my_pointer_struct = MyPointerStruct(cast(0, felt*));
+                // then the value is 0 and we should return `self.var.address`
+                let pointer_value = self.var.value.as_ref();
+
+                match pointer_value {
+                    Some(MaybeRelocatable::RelocatableValue(rel)) => Ok(Some(*rel)),
+                    Some(MaybeRelocatable::Int(_)) => Ok(self.var.address),
```
Comment (Eikix) [inline crates/cairo-addons/src/vm/vm_consts.rs:330]: are we saying that here, we expect `Some(MaybeRelocatable::Int(0))`?

should we use only Some(MaybeRelocatable::Int(0)) and fail otherwise?

Comment (enitrat) [reply crates/cairo-addons/src/vm/vm_consts.rs:330]: Technically it could be any non pointer value not just 0

Comment (enitrat) [reply crates/cairo-addons/src/vm/vm_consts.rs:330]: it's not based on what "we" want it's based on VM rules, you can cast any felt to a felt*
